import os
import numpy as np
from argparse import ArgumentParser

# 训练参数

parser = ArgumentParser()

parser.add_argument('--train_epoch', type=int, default=300)
parser.add_argument('--batch_size', type=int, default=64)
parser.add_argument('--lr', type=float, default=0.0005)
parser.add_argument('--lr_warmup', type=bool, default=True)
parser.add_argument('--total_epoch', type=int, default=5)
parser.add_argument('--lr_decrease', type=str, default='cos', help='the methods of learning rate decay  ')
parser.add_argument('--mixup', type=bool, default=False, help='using mixup or not')
parser.add_argument('--mixup_alpha', type=float, default=0.2)
parser.add_argument('--weight_decay', type=float, default=1e-3)
parser.add_argument('--momentum', type=float, default=0.90)
parser.add_argument('--class_num', type=int, default=15)
parser.add_argument('--retrain', type=bool, default=False, help='Separate training for the same training process')
parser.add_argument('--log_interval', type=int, default=10, help='How many batches to print the output once')
parser.add_argument('--save_interval', type=int, default=10, help='How many batches to save the model once')
parser.add_argument('--model_root', type=str, default='../output/models/')
parser.add_argument('--log_root', type=str, default='../output/logs/')
parser.add_argument('--modal', type=str, default='multi')
parser.add_argument('--model_name', type=str, default='mnist_cnn_best')
parser.add_argument('--log_name', type=str, default='.csv')
parser.add_argument('--backbone', type=str, default='couple_cross_fc')
parser.add_argument('--patch_size', type=int, default=7)
parser.add_argument('--p', default=[0, 0], help='para for modality dropout')
parser.add_argument('--location',type=str,default='after')

parser.add_argument('--labma_unimodal', type=float, default=1.0)
parser.add_argument('--data_root', type=str, default='Huston2013')
parser.add_argument('--pair_modalities', type=str, default='hsi+lidar')
parser.add_argument('--l1_loss', type=float, default=0.003)
parser.add_argument('--gama', type=float, default=1.003)
parser.add_argument('--osc', type=float, default=0.8)
parser.add_argument('--t_max', type=float, default=2.0)
parser.add_argument('--gpu', type=int, default=1)
parser.add_argument('--version', type=int, default=0)
parser.add_argument('--loss_num', type=int, default=3)
parser.add_argument('--figure_root', type=str, default='../output/depose/')
parser.add_argument('--vis_interval', type=int, default=50)
parser.add_argument('--identity', type=str, default='mcl')
parser.add_argument('--threshold', type=float, default=0.0)
parser.add_argument('--lambda0', type=float, default=1)
parser.add_argument('--lambda1', type=float, default=0.5)
parser.add_argument('--lambda2', type=float, default=0.5)
parser.add_argument('--lidar_lambda', type=float, default=1)

args = parser.parse_args()
args.pair_modalities = args.pair_modalities.split('+')
args.data_root = '../data/' + args.data_root
os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpu)
args.name = args.pair_modalities[0] + "_" + args.pair_modalities[1]+str(args.identity)
args.model_root = args.model_root + str(args.identity)
args.log_root = args.log_root+ str(args.identity)
args.model_root = args.model_root + str(args.identity)
args.figure_root = args.figure_root+ str(args.identity)
